create table
    public.manual_review_inbox (
                                   id bigint generated by default as identity,
                                   cid character varying not null,
                                   account character varying not null,
                                   media_type character varying not null,
                                   status character varying not null,
                                   created_at timestamp with time zone not null default now(),
                                   constraint manual_review_inbox_pkey primary key (id),
                                   -- The below really should be an int, but this is better ergonomics for the hackathon
                                    CONSTRAINT statuses CHECK (status IN ('pending', 'accepted', 'rejected'))
) tablespace pg_default;

CREATE UNIQUE INDEX manual_review_inbox_cid_account_media_type_idx
    ON public.manual_review_inbox USING btree
    (cid COLLATE pg_catalog."default", account COLLATE pg_catalog."default")
    TABLESPACE pg_default;

CREATE INDEX manual_review_account_status_idx
    ON public.manual_review_inbox USING btree
    (account COLLATE pg_catalog."default", status COLLATE pg_catalog."default")
    TABLESPACE pg_default;